# @package suite
defaults:
  - _self_
  - task: franka_env

suite: franka_env
name: "franka_env"

# obs dims
img_size: [640, 480] # (width, height)
use_robot_points: true
num_robot_points: 9
gt_depth: false

# action compute
point_dim: 3 # 2 or 3

# object points
use_object_points: true
num_object_points: ${suite.task.num_object_points}

# task settings
action_repeat: 1
hidden_dim: 256

# train settings
num_train_steps: 100100
log_every_steps: 100
save_every_steps: 10000
history: true
history_len: 10

# eval
eval_every_steps: 200000
num_eval_episodes: 5
eval_history_len: 10

# data loading
action_after_steps: 1

# obs_keys
pixel_keys: ["pixels1", "pixels2"]
proprio_key: "proprioceptive"
feature_key: "features"

# snapshot
save_snapshot: true

# force
force_controller: false
read_force: true
desired_force: 80
force_match_tolerance: 5
predict_force: true
mask_force: false
variable_desired_force: false
continuous_gripper: false
subsample: 3

task_make_fn:
  _target_: suite.point_policy.make
  task_name: ${suite.task.task_name}
  object_labels: ${suite.task.object_labels}
  action_repeat: ${suite.action_repeat}
  height: ${suite.img_size[1]}
  width: ${suite.img_size[0]}
  max_episode_len: ??? # to be specified later
  max_state_dim: ??? # to be specified later
  calib_path: ${root_dir}/calib/calib.npy
  eval: ${eval} # eval true mean use robot
  pixel_keys: ${suite.pixel_keys}
  use_robot_points: ${suite.use_robot_points}
  num_robot_points: ${suite.num_robot_points}
  use_object_points: ${suite.use_object_points}
  num_object_points: ${suite.num_object_points}
  points_cfg: ??? # to be specified later
  use_gt_depth: ${suite.gt_depth}
  point_dim: ${suite.point_dim}
  force_controller: ${suite.force_controller}
  read_force: ${suite.read_force}
  desired_force: ${suite.desired_force}
  force_match_tolerance: ${suite.force_match_tolerance}
  variable_desired_force: ${suite.variable_desired_force}
  continuous_gripper: ${suite.continuous_gripper}
