defaults:
  - _self_
  - agent: point_policy
  - suite: point_policy
  - dataloader: point_policy
  - override hydra/launcher: submitit_local

# Dir
root_dir: /home/wsi3567/Point-Policy
data_dir: /home/wsi3567/Point-Policy/Franka-Teach/data/processed_data_pkl/expert_demos

# misc
seed: 2
device: cuda
save_video: true
use_tb: true
batch_size: 64

# experiment
num_demos_per_task: 50
policy_head: deterministic
use_proprio: false
eval: false
experiment: train
experiment_label: ${policy_head}

# action chunking
temporal_agg: true # aggregate actions over time
num_queries: 20

# expert dataset
expert_dataset: ${dataloader.bc_dataset}

# Load weights
load_bc: false
bc_weight: /home/wsi3567/Point-Policy/point_policy/exp_local/2026.02.12/point_policy/deterministic/090813_hidden_dim_256/snapshot/100000.pt

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${experiment}/${experiment_label}/${now:%H%M%S}_hidden_dim_${suite.hidden_dim}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
